### ISSUE TITLE
notifier service hangs on empty slack 'webhook_url'

### ISSUE THREAD

**Issue by arbeit** [GoogleCloudPlatform/forseti-security#1275]
Found in `2.0-dev`. When the notifier config looks like this

```yaml
    - name: slack_webhook_pipeline
      configuration:
        webhook_url: ''
```
and the notifier is run it gets hung up and never terminates:

```
$ forseti --endpoint [::]:50051 notifier run
Retrieved 43 violations for resource 'policy_violations'
Running 'email_violations_pipeline' for resource 'policy_violations'
Running 'gcs_violations_pipeline' for resource 'policy_violations'
Running 'slack_webhook_pipeline' for resource 'policy_violations'
```
