### ISSUE TITLE
Allow users to specify whether they want the violations attachment to be json or csv format.

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1287]
By default, CSV is preferred.  But we should allow users to select json, if they prefer or there is a need to output hierarchical data structure.  This configurable option should be part of the notification configuration schema.

**Comment by arbeit** [comment]
How about adding an optional `data_format` field to the configuration stanza of notifiers. Example
```yaml
    resources:
        - resource: policy_violations
          should_notify: true
          notifiers:
            # Upload violations to GCS.
            - name: gcs_violations
              configuration:
                # gcs_path should begin with "gs://"
                gcs_path: 'gs://fsv/scanner_violations'
                data_format: 'json'
```
