### ISSUE TITLE
Scanners not all working for root resource being a Folder?

### ISSUE THREAD

**Issue by rllin-fathom** [GoogleCloudPlatform/forseti-security#2030]
I am trying out v2.4.0 in order to have my Forseti instance monitor a Folder rather than an entire organization.

This was my deployment process:
1. deployed with install script via google cloud shell
2. modified server config in GCS to use a folder as a root
3. modifier server config to use GCS rules

I then verified that my install was working by turning on the `enabled_api` rule and only whitelisting the logging api.  I expected this to trigger violations for all the other api's I have enabled.  It did 😄 

Issue:
Many violations that I expect to be triggered were not.  For example.  I changed my `service_account_key_rules.yaml` rule to trigger violations if service account keys were older than 1 day

```
rules:
  # The max allowed age of user managed service account keys (in days)
  - name: Service account keys not rotated
    resource:
      - type: project
        resource_ids:
          - '*'
    max_age: 1 # days
```

This scanner did not trigger any violations.  I verified the following things:

1. I checked through console that I have service account keys in a project in this folder which were last rotated > 5 days ago.
2. I looked directly in the CloudSQL instance and only the enabled_api violations appear.

I have other scanner rules which are not as easily described which are also not creating violations when they should be.  I chose these two examples for ease of illustration.
