### ISSUE TITLE
IAM scanner whitelisting without enumerating all roles

### ISSUE THREAD

**Issue by rllin-fathom** [GoogleCloudPlatform/forseti-security#2059]
split out from https://github.com/GoogleCloudPlatform/forseti-security/issues/2055#issuecomment-425527856

Summary:
IAM scanner whitelisting only considers roles with rules.  If a role does not have a rule, it is automatically whitelisted.

The desire is to have an exact way of describing whitelist rules.  One way to do this is to reflect all GDM declarative role bindings, and any deviation from that would trigger violations.

Currently, this would require enumerating rules for all predefined roles, all custom roles, and all untracked (maliciously created or not) custom roles (and creating dummy users https://github.com/GoogleCloudPlatform/forseti-security/issues/1963).

This is hard to scale because:

1. there are > 200 predefined roles
2. custom roles can be large in number also.  the declaration of new custom roles is coupled with the need to add a new forseti rule
3. open to malicious agent that creates a custom role that does not have a corresponding iam rule.

**Comment by blueandgold** [comment]
@rllin-fathom There is a way to apply a rule to all the roles.  Here are a couple of examples:

```
rules:
  - name: Allow only members of my org to be in any role
    mode: whitelist
    resource:
      - type: organization
        applies_to: self_and_children
        resource_ids:
          - '*'
    inherit_from_parents: true
    bindings:
      - role: roles/*
        members:
          - user:*@henrychang.mygbiz.com
          - serviceAccount:*@*.gserviceaccount.com
```
```
rules:
  - name: Don't allow gmail users to be in any role
    mode: blacklist
    resource:
      - type: organization
        applies_to: self_and_children
        resource_ids:
          - '*'
    inherit_from_parents: true
    bindings:
      - role: roles/*
        members:
          - user:*@gmail.com
```
