### ISSUE TITLE
Location scanner cannot express specific locations for resources 

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/forseti-security#2128]
e.g. I want bucket 'foo' to be in 'us'.

Currently the location scanner applies to all buckets in a project, folder or organization. We want it to apply to specific resource ids as well.

Proposal: change applies_to from just a list of strings to a list of resources.

e.g. the rule above would be expressed as:

```
rules:
  - name: rule.
    mode: whitelist
    resource:
      - type: organization
        resource_ids:
          - org-1
    applies_to:
      - type: bucket
        resource_ids:
           - foo
    locations:
      - 'us'
```

resource_ids can be * as well.
