### ISSUE TITLE
External Project Access Scanner Rule - Specify User

### ISSUE THREAD

**Issue by kevensen** [GoogleCloudPlatform/forseti-security#2525]
**Version:** 2.10.0
**Module:** External Project Access Scanner

Currently, the rules for the External Project Access Scanner allow for the whitelisting of organizations and folders as ancestors of a GCP Project.
```yaml
rules:
- name: Only allow access to projects in my organization.
  allowed_ancestors:
  - organizations/{ORGANIZATION_ID}
```
It is desirable to annotate the rule so that it can be applied to specific users.
```yaml
rules:
- name: Only allow access to projects in my organization.
  allowed_ancestors:
  - organizations/{ORGANIZATION_ID}
  users:
  - user1@example.com
  - user2@example.com
```
The **user** stanza would be optional.  Omitting it would mean that the rule applies to all users in the organization.
