### ISSUE TITLE
Deployment Manager Cloud Storage template creates bucket in wrong location

### ISSUE THREAD

**Issue by marcin-kolda** [GoogleCloudPlatform/forseti-security#476]
When I installed Forseti using setup wizard (using version 1.0.3-pre), then cloud storage bucket was created in wrong location.

I wanted to create a bucket in London region and template was generated properly:
```yaml
# Cloud Storage
- name: forseti-bucket-name
  type: bucket.py
  properties:
    region: europe-west2
```
Instead of regional bucket in europe-west2, Deployment Manager created multi-regional bucket in US.
