### ISSUE TITLE
Required rules incorrectly report violations even if the "required" member is found in the IAM policy

### ISSUE THREAD

**Issue by carise** [GoogleCloudPlatform/forseti-security#711]
For this rule:

```
  - name: All projects must have owner from my domain
    mode: required
    resource:
      - type: project
        applies_to: self
        resource_ids:
          - '*'
    inherit_from_parents: true
    bindings:
      - role: roles/owner
        members:
          - 'user:*@MYDOMAIN'
```

Still seeing policy violations, even if the project IAM has a policy binding with an owner in the domain. #
