### ISSUE TITLE
Unexpected Violations from IAM Policy Scanner (Allow service accounts to have access)

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#750]
After running the iam scanner from the up-to-date dev branch, there are some unexpected violations from the ```Allow service accounts to have access``` rule, such as users in the domain users, who have other iam roles.

Using this default rule:
```
  # custom rules
  - name: Allow service accounts to have access
    mode: whitelist
    resource:
      - type: organization
        applies_to: self_and_children
        resource_ids:
          - '*'
    inherit_from_parents: true
    bindings:
      - role: roles/*
        members:
          - serviceAccount:*@*.gserviceaccount.com
```

Example output:
```
660570133860,organization,1,Allow service accounts to have access,ADDED,{'member': u'user:felix@henrychang.mygbiz.com'\, 'role': u'roles/billing.viewer'}
660570133860,organization,1,Allow service accounts to have access,ADDED,{'member': u'user:iamux-tester@henrychang.mygbiz.com'\, 'role': u'roles/iam.serviceAccountTokenCreator'}
660570133860,organization,1,Allow service accounts to have access,ADDED,{'member': u'user:felix@henrychang.mygbiz.com'\, 'role': u'roles/iam.serviceAccountAdmin'}
660570133860,organization,1,Allow service accounts to have access,ADDED,{'member': u'user:henry@henrychang.mygbiz.com'\, 'role': u'roles/iam.serviceAccountAdmin'}
660570133860,organization,1,Allow service accounts to have access,ADDED,{'member': u'user:iamux-tester@henrychang.mygbiz.com'\, 'role': u'roles/iam.serviceAccountAdmin'}
660570133860,organization,1,Allow service accounts to have access,ADDED,{'member': u'user:felix@henrychang.mygbiz.com'\, 'role': u'roles/billing.projectManager'}
660570133860,organization,1,Allow service accounts to have access,ADDED,{'member': u'user:felix@henrychang.mygbiz.com'\, 'role': u'roles/logging.viewer'}
660570133860,organization,1,Allow service accounts to have access,ADDED,{'member': u'user:carise@henrychang.mygbiz.com'\, 'role': u'roles/resourcemanager.folderCreator'}
```
